-- supabase/migrations/TIMESTAMP_create_tables.sql
CREATE TABLE nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  query TEXT,
  response TEXT,
  summary TEXT,
  parent BIGINT,
  color TEXT DEFAULT '#6495ED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);