-- supabase/migrations/TIMESTAMP_create_tables.sql
CREATE TABLE nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  content TEXT,
  response TEXT,
  from_node BIGINT,
  color TEXT DEFAULT '#6495ED',
  created_at TIMESTAMPTZ DEFAULT NOW()
);


CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE node_embeddings (
  node_id BIGINT PRIMARY KEY REFERENCES nodes(id) ON DELETE CASCADE,
  embedding vector(1536),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);